GET http://localhost:3001/user/statement/1614628133/1617306533 HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGVuYXJhbmdlbC5uQGdtYWlsLmNvbSIsImlhdCI6MTYxNjQ0MTQ0NSwiZXhwIjoxNjE3MzA1NDQ1fQ.P6hMHWHEmnJi5zn6WR6k8vu4UHmWLKBFNJv78Q_UOhg